#!/usr/bin/env bash

use () { echo "Usage: $0 file_task count_treds"; }

getline () { head -${1} < "$2" | tail -1; }

if [ $# -ne 2 ]; then
  use
  exit 1
fi

thread () {
  echo "${4}_" >> "$3"
  LINE=`grep -n "^${4}_" $3 | tail -1 | cut -d":" -f 1`
  while [ $LINE -le $2 ]; do
    if test ! -f "$1";then 
      exit;
    fi
    if test ! -f $3;then
      exit;
    fi
    command=`getline $LINE "${1}"`
    echo $command | bash
    if test ! -f $3;then
      exit;
    fi
    echo "${4}_" >> "$3"
    LINE=`grep -n "^${4}_" $3 | tail -1 | cut -d":" -f 1`
  done
}

if [ $# -eq 2 ]; then
  i=$2
  if [ $i -eq 0 ];then
    use
    exit 1;
  fi
  FILE="/tmp/$(basename $0).$RANDOM.txt"
  while test -f ${FILE};do
    FILE="/tmp/$(basename $0).$RANDOM.txt"
  done
  touch ${FILE}
  trap "rm '$FILE'" EXIT
#  echo $FILE # show file name
  LINES=`wc -l <"$1"`
  while [ "$i" -gt 0 ]; do
    i=`expr "$i" - 1`
    thread $1 $LINES $FILE $i &
  done
  while :;do
    wait
    if [ "$?" -eq 0 ]; then
      break
    fi
  done
fi
